name: Docker Image (Snapshot/Tag)

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # See https://github.com/docker/metadata-action#readme
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}/subversion/snapshot
          # generate Docker tags based on the following events/attributes
          tags: |
            type=match,pattern=subversion-(.*),group=1
      # See https://github.com/docker/login-action
      - name: Log In To The GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # See https://github.com/docker/build-push-action#readme
      # See https://github.com/docker/build-push-action/blob/b1aeb1103e6b3b5648dbd6deaf0559919456ca6b/docs/advanced/tags-labels.md
      - name: Build And Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/arm64,linux/amd64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
